using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Even_Fibonacci_numbers
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms");
            int num1 = 1;
            int num2 = 2;
            Console.WriteLine("The terms are:");
            Console.WriteLine();
            Console.Write(num1 + ", ");
            Console.Write(num2 + ", ");
            int total = 2;           
           while(num2 <= 4000000 || num1 <= 4000000)
            {

                num1 += num2;
                num2 = num1 + num2;
                Console.Write(num1 + ", " + num2 + ", ");
                if (num1 % 2 == 0)
                {
                    total += num1;
                }
                if (num2 % 2 == 0)
                {
                    total += num2;
                }



            }
            Console.WriteLine();
            Console.WriteLine();
            Console.Write("The answer is " + total);
            Console.ReadKey(true);



        }
    }
}
